### ISSUE TITLE
Where should put the LLM directory?

### ISSUE THREAD

**Issue by wikeeyang** [kijai/ComfyUI-llama-cpp#1]
大佬，你这节点的 LLM 目录，该创建在啥位置，放在：ComfyUI\LLM、ComfyUI\custom_nodes\ComfyUI-llama-cpp\LLM、ComfyUI\models\LLM 几个位置，都找不到 gguf 模型文件，请大佬给个指示，谢谢！

**Comment by wikeeyang** [comment]
找到了，重新启动 ComfyUI，在 ComfyUI\models\LLM 能找到了。。。😂

**Comment by Innomen** [comment]
Incredible that I had to search here to find this. Why does nothing just have input boxes or file pickers? /smh Anyway, what you do for english speakers is you make an LLM folder in the comfyui models folder and drop them in there then just refresh the page. Now... for how to get a box "output" expects.
